---

- name: Check if Visual Studio Code is intalled
  command: dpkg-query -W code
  register: check_code
  failed_when: false
  changed_when: false

- name: Install VS Code
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868
    state: present
  become: true
  when: check_code.rc == 1

- name: Install slack repo key
  apt_key:
    url: "{{ apt_slack_repo_key }}"
    state: present

- name: Install Slack repository
  apt_repository: 
    repo: "{{ apt_slack_repo }}"
    mode: 0644
    state: present

- name: Update the apt cache
  apt:
    cache_valid_time: 3600
    update_cache: yes

- name: Slack Install packages
  apt:
    pkg: "slack-desktop"
    state: present
