---

- name: update .vimrc in home folder.
  copy:
    src: .vimrc
    dest: /home/{{ username }}/.vimrc

- name: make vim color directory
  file:
    path: /home/{{ computer }}/.vim/colors 
    state: directory

- name: create lucario vim color
  copy:
    src: lucario.vim
    dest: /home/{{ username }}/.vim/colors/lucario.vim

#- name: Download lucario color scheme
#  get_url
#    url: https://raw.githubusercontent.com/raphamorim/lucario/master/colors/lucario.vim
#    dest: /home/{{ username }}/.vim/colors
#    checksum: sha256:03c5c9d88bb3e101071839a96ba4708731dc9465f2d757a26e33592e8620c403

