---

- name: Add tlp repo
  apt_repository: repo='ppa:linrunner/tlp' state=present
  when: ansible_distribution == "Ubuntu"

- name: install packages
  become: true
  apt: 
    name: "{{ item }}" 
    state: present 
    update_cache: yes 
    cache_valid_time: 3600
  with_items:
    - make
    - curl
    - vim
<<<<<<< HEAD
=======
    - apt-transport-https
>>>>>>> 5d260598c89785bf8d38acef02378097c1be92f5
    - wireshark-qt
    - chromium-browser
    - keepassx
    - pidgin        
    - git
    - jq
    - htop
    - python3-pip
    - python3-dev
    - python-dev
    - powertop
    - tlp 
    - tree
    - virtualbox-qt
    - virtualbox-dkms
    - nodejs
    - npm
    - p7zip-full



- name: Auto-tune powertop
  command: /usr/sbin/powertop --auto-tune

- name: force synaptics driver for touch pad
  copy:
    src: 60-touchpad.conf
    dest: /usr/share/X11/xorg.conf.d/60-touchpad.conf
    owner: root
    group: root
    mode: 0644
