---

- name: Add tlp repo
  apt_repository: repo='ppa:linrunner/tlp' state=present


- name: install packages
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - curl
    - make
    - vim
    - wireshark
    - chromium-browser
    - keepassx
    - git
    - python3-pip
    - python3-dev
    - python-dev
    - powertop
    - tlp 
    - tree

- name: Install slack
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-3.1.1-amd64.deb
    state: present
  become: true

- name: Install VS Code
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868
    state: present
  become: true

