---

- name: update all packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: install packages
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
